stages:
  - archiving
  - deploy

variables:
  PROJECT_NAME: $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME

archive:
  image: node:lts
  stage: archiving
  only:
    - main
    - develop
    - next
  when: on_success
  before_script:
    - apt-get update
    - apt-get install zip -y
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - .yarn-cache/
  script:
    - yarn install --frozen-lockfile  --cache-folder .yarn-cache
    - yarn build
    - zip -r $PROJECT_NAME-server.zip .output/server
  artifacts:
    paths:
      - $PROJECT_NAME-server.zip
      - .output/public/

deploy:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --version
    - aws lambda update-function-code --function-name $AWS_LAMBDA_NAME --zip-file fileb://$PROJECT_NAME-server.zip
    - aws s3 cp .output/public/ s3://$AWS_BUCKET_NAME --recursive --cache-control max-age=31536000  --delete --acl public-read 
