stages:
  - archiving
  - deploy

variables:
  PROJECT_NAME: $CI_PROJECT_NAME-$CI_COMMIT_REF_NAME

archive:
  stage: archiving
  only:
    - main
    - develop
    - next
  image: ubuntu
  when: on_success
  before_script:
    - apt-get update
    - apt-get install zip -y
  script:
    - yarn install --frozen-lockfile
    - yarn build
    - zip -r $PROJECT_NAME.zip .output
  artifacts:
    paths:
      - $CI_PROJECT_NAME.zip

deploy:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --version
    - aws lambda update-function-code --function-name hello-world --zip-file fileb://$PROJECT_NAME.zip
